version: '3'

services:
  quizYnov:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_PASSWORD: 12345!
      MYSQL_ROOT_PASSWORD: 12345!
      MYSQL_DATABASE: quiz_ynov_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  cache:
    image: redis:7.2-alpine
    restart: always
    ports:
    - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 12345!
    volumes: 
    - cache:/data
volumes:
  quizYnov:
  cache:
    driver: local  